// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-vxCWoIbKcxABhsFf86mTmw-sh4NN5g',
    appId: '1:875826680253:web:1e46d8c3f05a02aec302d4',
    messagingSenderId: '875826680253',
    projectId: 'truli-smart',
    authDomain: 'truli-smart.firebaseapp.com',
    storageBucket: 'truli-smart.appspot.com',
    measurementId: 'G-K3LR00CKQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBcFpbGgrX9siVk1XWqdYLJn_kl7aoQoU',
    appId: '1:875826680253:android:39bb5523319aeb95c302d4',
    messagingSenderId: '875826680253',
    projectId: 'truli-smart',
    storageBucket: 'truli-smart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAooMN6J0RkYYLX4ys1QSEV4akiKXlDisE',
    appId: '1:875826680253:ios:83ec31fc405f0c4cc302d4',
    messagingSenderId: '875826680253',
    projectId: 'truli-smart',
    storageBucket: 'truli-smart.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAooMN6J0RkYYLX4ys1QSEV4akiKXlDisE',
    appId: '1:875826680253:ios:472cb54625b2f6c7c302d4',
    messagingSenderId: '875826680253',
    projectId: 'truli-smart',
    storageBucket: 'truli-smart.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
